#!/bin/bash

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SETTINGS="$HERE/settings.cfg"
if [ -s $SETTINGS ];
then
    source $SETTINGS;
else
    echo "'$SETTINGS' not found!"
    exit 1
fi

output=""
has_error=0
today=$(date +"%d %h %Y, %H:%M")

while read line
do
    check=`curl -s -D - $line --head -o /dev/null`

    if [ $? == "0" ]; then

        match=`grep "HTTP/... [45]0[0-9]" <<< "$check"`

        if [ $? == "0" ]; then
            output="$output\nHouve problema com $line, erro $match"
            has_error=1
        else
            output="$output\n$line esta ok"
        fi

    else
        output="$output\nNao pude conectar em $line"
        has_error=1
    fi

done < $sites_file
output="$output\n\n$today"

if [ $has_error -eq 1 ];
then
    echo -e $output | mail -s "Sites com problemas - $today" $team_mail 2> /tmp/mailerror
else
    echo -e $output | mail -s 'Relatorio dos sites' $admin_mail 2> /tmp/mailerror
fi

